# -*- coding: utf-8 -*-
"""
/***************************************************************************
 kolba
                                 A QGIS plugin
 Плагин, позволяющий запускать экспериментальные функции
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-22
        copyright            : (C) 2023 by Pavel Pereverzev
        email                : pasha004@yandex.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load kolba class from file kolba.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .kolba import kolba
    return kolba(iface)
